// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGHSS.Api.Data;

#nullable disable

namespace SGHSS.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SGHSS.Api.Models.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Motivo")
                        .HasColumnType("longtext");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("ProfissionalSaudeId")
                        .HasColumnType("int");

                    b.Property<int?>("ProntuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceitaDigitalId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProfissionalSaudeId");

                    b.HasIndex("ReceitaDigitalId");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("SGHSS.Api.Models.Internacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LeitoId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasColumnType("longtext");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeitoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("Internacoes");
                });

            modelBuilder.Entity("SGHSS.Api.Models.Leito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.Property<int>("UnidadeHospitalarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeHospitalarId");

                    b.ToTable("Leitos");
                });

            modelBuilder.Entity("SGHSS.Api.Models.MedicamentoPrescrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dosagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Duracao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Frequencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeMedicamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ReceitaDigitalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceitaDigitalId");

                    b.ToTable("MedicamentosPrescritos");
                });

            modelBuilder.Entity("SGHSS.Api.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("SGHSS.Api.Models.ProfissionalSaude", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RegistroProfissional")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UnidadeHospitalarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeHospitalarId");

                    b.ToTable("ProfissionaisSaude");
                });

            modelBuilder.Entity("SGHSS.Api.Models.Prontuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Anotacoes")
                        .HasColumnType("longtext");

                    b.Property<int>("ConsultaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Diagnostico")
                        .HasColumnType("longtext");

                    b.Property<string>("PlanoTratamento")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId")
                        .IsUnique();

                    b.ToTable("Prontuarios");
                });

            modelBuilder.Entity("SGHSS.Api.Models.ReceitaDigital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoValidacao")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ValidaAte")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ReceitasDigitais");
                });

            modelBuilder.Entity("SGHSS.Api.Models.UnidadeHospitalar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UnidadesHospitalares");
                });

            modelBuilder.Entity("SGHSS.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("int");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<int?>("ProfissionalSaudeId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PacienteId")
                        .IsUnique();

                    b.HasIndex("ProfissionalSaudeId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SGHSS.Api.Models.Consulta", b =>
                {
                    b.HasOne("SGHSS.Api.Models.Paciente", "Paciente")
                        .WithMany("Consultas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGHSS.Api.Models.ProfissionalSaude", "ProfissionalSaude")
                        .WithMany("Consultas")
                        .HasForeignKey("ProfissionalSaudeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGHSS.Api.Models.ReceitaDigital", "ReceitaDigital")
                        .WithMany()
                        .HasForeignKey("ReceitaDigitalId");

                    b.Navigation("Paciente");

                    b.Navigation("ProfissionalSaude");

                    b.Navigation("ReceitaDigital");
                });

            modelBuilder.Entity("SGHSS.Api.Models.Internacao", b =>
                {
                    b.HasOne("SGHSS.Api.Models.Leito", "Leito")
                        .WithMany()
                        .HasForeignKey("LeitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGHSS.Api.Models.Paciente", "Paciente")
                        .WithMany("Internacoes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leito");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("SGHSS.Api.Models.Leito", b =>
                {
                    b.HasOne("SGHSS.Api.Models.UnidadeHospitalar", "UnidadeHospitalar")
                        .WithMany("Leitos")
                        .HasForeignKey("UnidadeHospitalarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadeHospitalar");
                });

            modelBuilder.Entity("SGHSS.Api.Models.MedicamentoPrescrito", b =>
                {
                    b.HasOne("SGHSS.Api.Models.ReceitaDigital", "ReceitaDigital")
                        .WithMany("Medicamentos")
                        .HasForeignKey("ReceitaDigitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReceitaDigital");
                });

            modelBuilder.Entity("SGHSS.Api.Models.ProfissionalSaude", b =>
                {
                    b.HasOne("SGHSS.Api.Models.UnidadeHospitalar", "UnidadeHospitalar")
                        .WithMany("Profissionais")
                        .HasForeignKey("UnidadeHospitalarId");

                    b.Navigation("UnidadeHospitalar");
                });

            modelBuilder.Entity("SGHSS.Api.Models.Prontuario", b =>
                {
                    b.HasOne("SGHSS.Api.Models.Consulta", "Consulta")
                        .WithOne("Prontuario")
                        .HasForeignKey("SGHSS.Api.Models.Prontuario", "ConsultaId");

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("SGHSS.Api.Models.Usuario", b =>
                {
                    b.HasOne("SGHSS.Api.Models.Paciente", "Paciente")
                        .WithOne("Usuario")
                        .HasForeignKey("SGHSS.Api.Models.Usuario", "PacienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SGHSS.Api.Models.ProfissionalSaude", "ProfissionalSaude")
                        .WithOne("Usuario")
                        .HasForeignKey("SGHSS.Api.Models.Usuario", "ProfissionalSaudeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Paciente");

                    b.Navigation("ProfissionalSaude");
                });

            modelBuilder.Entity("SGHSS.Api.Models.Consulta", b =>
                {
                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("SGHSS.Api.Models.Paciente", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("Internacoes");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGHSS.Api.Models.ProfissionalSaude", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGHSS.Api.Models.ReceitaDigital", b =>
                {
                    b.Navigation("Medicamentos");
                });

            modelBuilder.Entity("SGHSS.Api.Models.UnidadeHospitalar", b =>
                {
                    b.Navigation("Leitos");

                    b.Navigation("Profissionais");
                });
#pragma warning restore 612, 618
        }
    }
}
